version: "3.7"

services:
  frontend:
    container_name: "component-examples"
    image: "component-examples"
    restart: "unless-stopped"
    build:
      context: "."
      dockerfile: "./Dockerfile"
      target: "development"
    command: "npm run dev"
    volumes:
      - "./src:/app/src:rw"
    ports:
      - 3020:5173
